### PR TITLE
WIP: support flat config

### PR DESCRIPTION
**Pull request by schreibse**
## Goal
The goal of this pr is to support the new flat-config `eslint.config.js` of eslint as well as the legacy config `.eslintrc.json`

## Resources
- [ESLint Migration Rules](https://eslint.org/docs/latest/extend/plugin-migration-flat-config#migrating-rules-for-flat-config)
- [ESLint Breaking Changes](https://eslint.org/docs/latest/use/migrate-to-9.0.0#breaking-changes-for-plugin-developers)
- [AngularESLint](https://github.com/angular-eslint/angular-eslint)

## To Be Discussed
- [ ] Should schematics for the angular cli added in this pr as well or better in a separate pr

## Todo
- [x]  flat-config works
- [x] legacy config works
- [ ] ensure tests cover both configurations
- [ ] update docs
- [ ] add to [ESLint Tracking: Flat Config support](https://github.com/eslint/eslint/issues/18093)

## Note
Changes are heavily influenced by [AngularESLint](https://github.com/angular-eslint/angular-eslint), [JamesHenry](https://github.com/JamesHenry) did a lot of work for the v18 of @angular-eslint

@rainerhahnekamp: Please let me know your thoughts, any feedback is highly appreciated

### CODE REVIEW

**Comment by rainerhahnekamp** [comment]
Hey @schreibse, cool stuff. I see that most changes relate to typescript-eslint. I guess that one should have been there all the time, right?

Just a coincidence that Sheriff worked until now. Probably because anguar-eslint included typescript-eslint already. :)

**Comment by schreibse** [comment]
> Hey @schreibse, cool stuff. I see that most changes relate to typescript-eslint. I guess that one should have been there all the time, right?
> 
> Just a coincidence that Sheriff worked until now. Probably because angular-eslint included typescript-eslint already. :)

I think so yes, although I did not test it with a vanilla workspace without angular-eslint.

Great news, I was able to get it to work for both legacy-config as well as flat-config 🎉

## Legacy

- Angular 18 workspace
- `"eslint": "8.57.0"`
- ng add @angular-eslint/schematics (v18)

.eslintrc.json
```
{
  "root": true,
  "overrides": [
    {
      "files": ["**/*.ts"],
      "extends": ["plugin:@softarc/sheriff/legacy"]
    }
  ]
}
```

Shows the expected sheriff errors:
```
C:\Dev\eslint-legacy-config\src\app\app.component.ts
  3:1  error  module  cannot access \src\app\holidays\data. Tags [root] have no clearance for type:data  @softarc/sheriff/dependency-rule

C:\Dev\eslint-legacy-config\src\app\holidays\feature\holiday.component.ts
  2:1  error  Deep import is not allowed. Use the module's index.ts or path  @softarc/sheriff/deep-import
```

## Flat Config

- Angular 18 workspace
- `"eslint": "^9.3.0"`
- ng add @angular-eslint/schematics (v18)

eslint.config.js
```
const tseslint = require('typescript-eslint');
const softarceslint = require('@softarc/eslint-plugin-sheriff');

module.exports = tseslint.config(
  {
    ignores: [
      '.angular/',
      '.husky/',
      '.vscode/',
      'dist/',
      'node_modules/',
      'ssl/',
      'index.ts',
      'jest.config.ts',
      'jest.preset.ts',
      'test-setup.ts',
      'sheriff.config.ts',
    ],
  },
  {
    files: ['**/*.ts'],
    extends: softarceslint.configs.flat,
  }
);
```

Shows the expected sheriff errors:
```
C:\Dev\eslint-flat-config\projects\eslint-flat-config\src\app\app.component.ts
  4:1  error  module  cannot access \projects\eslint-flat-config\src\app\holidays\data. Tags [root] have no clearance for type:data  @softarc/sheriff/dependency-rule

C:\Dev\eslint-flat-config\projects\eslint-flat-config\src\app\holidays\feature\holiday.component.ts
  2:1  error  Deep import is not allowed. Use the module's index.ts or path  @softarc/sheriff/deep-import
```

I noticed that for the legacy config it was enough to specify `"files": ["*.ts"],`, however I needed to change that for the flat config -> `files: ['**/*.ts']`. That is of course expected, I am surprised it works with out the **/ wildcard for the legacy.

Please let me know what you think (I also updated the inital post of this pr for a better overview), thank you 🙌

**Comment by rainerhahnekamp** [comment]
Thanks, Stephan; I will give it a try tomorrow. You are the expert, so I will just try it out on my machine. If everything else looks fine, I could merge it.

One important thing, though: I have to merge (and release) the PR for the CLI. As far as I see it, it doesn't affect your changes in any way, so you might have to rebase after me.

**Comment by schreibse** [comment]
> Thanks, Stephan; I will give it a try tomorrow. You are the expert, so I will just try it out on my machine. If everything else looks fine, I could merge it.
> 
> One important thing, though: I have to merge (and release) the PR for the CLI. As far as I see it, it doesn't affect your changes in any way, so you might have to rebase after me.

yeah, the rebase is no problem. It would be best to add more tests and update the docs before merging though. I ll look into that asap

**Comment by rainerhahnekamp** [comment]
Yes, we should probably also add a fresh Angular 18 project to the test-projects folder where we have a working example but can also use it for integration tests.

If you look at the github actions, there are some integration tests at the very end which run sheriff against a real application.

Documentation would also be great!

**Comment by schreibse** [comment]
short update: I did a rebase (15.0.1 release) and added a new angular-18 project (angular-iiii) with the angular cli. Unfortunately I have trouble figuring out the whole test setup, so help would be appreciated 🙌

**Comment by rainerhahnekamp** [comment]
Great!

I'd say we should just verify that in angular-iiii (maybe angular-iv), eslint is detecting an error. That should be enough to verify that the flat config works.

`./run-integration.test.sh` triggers the test in the projects. At the moment, it is just angular-i and typescript. You would have to add an `integration-test.sh` to the Angular 18 project. You can copy the `integration-test.sh` from `angular-i`.

In my opinion, we don't need to copy all the tests from `angular-i` but only the "Deep Import Check". If that one causes eslint to produce erros, we know that the flat config is working.

**Comment by rainerhahnekamp** [comment]
I've already merged it to main, but the build broke, and I had to reset it.

I squashed your commits and moved them into 9fbf548. I would add their some corrections on top of it and would then merge two commits (yours & mine) wants it is stable. You will of course keep the authorship.

Thanks so far.

**Pull request merged**
