### PR TITLE
Feat/eslint flat

### PR DESCRIPTION
**Pull request by rainerhahnekamp**

### CODE REVIEW

**Comment by rainerhahnekamp** [comment]
Closes #87

**Comment by rainerhahnekamp** [comment]
Thanks @schreibse

**Comment by schreibse** [comment]
wow, that is amazing to see. Unfortunately there was still so much work required, I just skimmed through the changes and I realized pretty quickly why I was unable those tests / error messages

**Comment by rainerhahnekamp** [comment]
@schreibse The rest of the work revolved around the flat configuration. Mostly tests and moving to native ESLint

**Pull request merged**
